Updated INSTALLOS: install csv to json interpreter: mlr

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -42,13 +42,13 @@ else
     echo "\e[31mFixer not found.\e[0m"
 fi
 
-if [ $FPHP = 0 ]; then
-    echo -n ""
-elif [ -f phpstan.neon.dist ] && [ -f vendor/bin/phpstan ]; then
-    phpx vendor/bin/phpstan analyse || exit $?
-else
-    echo "\e[31mLarastan not found.\e[0m"
-fi
+# if [ $FPHP = 0 ]; then
+#     echo -n ""
+# elif [ -f phpstan.neon.dist ] && [ -f vendor/bin/phpstan ]; then
+#     phpx vendor/bin/phpstan analyse || exit $?
+# else
+#     echo "\e[31mLarastan not found.\e[0m"
+# fi
 
 if [ $FPHP = 0 ]; then
     exit 0
